apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lyiu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0055-tenant/ci1t-43256-0055-app/devfile-sample-lyiu@sha256:8f145cdbfb62cf49ba10a9becacc3f9390ca8319ca509347988dca9dc95d43ee
        name: my-nodejs
        resources: {}
status: {}
